# [supervisord]
# logfile=/dev/stdout
# logfile_maxbytes=0

[program:messenger-consume]
command=/usr/local/bin/run-messenger-consume.sh
autostart=true
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true
user=www-data
group=www-data
numprocs=4
startsecs=0
process_name=%(program_name)s_%(process_num)02d

[program:php-fpm]
command=/usr/local/bin/run-php-fpm.sh
autostart=true
autorestart=true
startretries=3
startsecs=1
user=www-data
group=www-data
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true
