api_platform:
  title: 'Qantis - MarketPlace API'
  description: 'Cette API expose des endpoint permettant de synchroniser la marketplace avec les données Uppler'
  version: '1.0.0'

  http_cache:
    public: false
    invalidation:
      enabled: false

  mapping:
    paths: ['%kernel.project_dir%/src/Entity', '%kernel.project_dir%/src/Dto']

  patch_formats:
    json: ['application/merge-patch+json']
    jsonld: ['application/ld+json']

  formats:
    jsonld:
      mime_types: ['application/ld+json']
    json:
      mime_types: ['application/json']
    xml:
      mime_types: ['application/xml', 'text/xml']
    yaml:
      mime_types: ['application/x-yaml']
    csv:
      mime_types: ['text/csv']
    html:
      mime_types: ['text/html']
    myformat:
      mime_types: ['application/vnd.myformat']

  swagger:
    api_keys:
      apiKey:
        name: Authorization
        type: header

  exception_to_status:
    # The 4 following handlers are registered by default, keep those lines to prevent unexpected side effects
    Symfony\Component\Serializer\Exception\ExceptionInterface: 400 # Use a raw status code (recommended)
    ApiPlatform\Exception\InvalidArgumentException: !php/const Symfony\Component\HttpFoundation\Response::HTTP_BAD_REQUEST
    ApiPlatform\Exception\FilterValidationException: 400
    Doctrine\ORM\OptimisticLockException: 409

    # Validation exception
    ApiPlatform\Symfony\Validator\Exception\ValidationException: !php/const Symfony\Component\HttpFoundation\Response::HTTP_UNPROCESSABLE_ENTITY

    # Custom mapping
    App\Exception\UserAccountException: 404 # Here is the handler for our custom exception
