when@prod:
  sentry:
    dsn: '%env(SENTRY_DSN)%'
    options:
      ignore_exceptions:
        - 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException'
        - 'Symfony\Component\Security\Core\Exception\AuthenticationException'
        - 'App\Exception\AutoLoginException'
        - 'Symfony\Component\HttpKernel\Exception\NotAcceptableHttpException'
        - 'Doctrine\DBAL\Exception\ConnectionException'
        - 'Doctrine\DBAL\Exception\ConnectionLost'
        - 'Symfony\Component\Console\Exception\CommandNotFoundException'
        - 'Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException'
        - 'App\Exception\MissingChannelHeaderException'
      send_default_pii: true
      enable_logs: true
    tracing:
      enabled: false

  services:
    Sentry\SentryBundle\Monolog\LogsHandler:
      arguments:
        - !php/const Monolog\Logger::INFO
