services:
  php:
    hostname: php-mkp
    image: 211737105908.dkr.ecr.eu-west-3.amazonaws.com/marketplace-php:local
    env_file:
      - .env
      - .env.dev
      - .env.local
    build:
      context: .
      target: php
    # Run as root to avoid permission issues locally
    # In prod www-data is used to run container
    user: root
    volumes:
      - ./:/var/www/
      - ./docker/php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php-fpm/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - dev-qantis
    depends_on:
      db:
        condition: service_healthy

  php-cron:
    image: 211737105908.dkr.ecr.eu-west-3.amazonaws.com/marketplace-php:local
    hostname: php-cron-mkp
    env_file:
      - .env
      - .env.dev
      - .env.local
    command: sh -c "bin/console cron:start --blocking -n"
    volumes:
      - ./:/var/www/
    environment:
      APP_ENV: dev
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - dev-qantis
    depends_on:
      php:
        condition: service_started

  js:
    hostname: js-mkp
    build:
      context: .
      target: node
    working_dir: /var/www
    command: >
      sh -c "yarn install
      && yarn docker"
    environment:
      - NODE_ENV=dev
    volumes:
      - ./:/var/www/
    ports:
      - '3003:3003'
    depends_on:
      - php
    networks:
      - dev-qantis

  nginx:
    image: 211737105908.dkr.ecr.eu-west-3.amazonaws.com/marketplace-nginx:refacto-Dockerfile5
    hostname: nginx-mkp
    build:
      context: .
      target: nginx
    environment:
      - PHP_URL=php-mkp
    depends_on:
      php:
        condition: service_started
      js:
        condition: service_started
    volumes:
      - ./:/var/www
      - ./var:/var/log/nginx
    ports:
      - '8087:80'
    networks:
      - dev-qantis

  db:
    image: postgres:17.5
    hostname: db-mkp
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mkp_db
    ports:
      - '15436:5432'
    volumes:
      - /var/lib/postgresql/data
    networks:
      - dev-qantis
    healthcheck:
      test: [ "CMD-SHELL", "psql -U postgres -c 'select 1' || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 12
      start_period: 3s

  maildev:
    image: maildev/maildev
    hostname: maildev-mkp
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    ports:
      - '8086:80'
    networks:
      - dev-qantis

networks:
  dev-qantis:
    name: dev-qantis

volumes:
  db-data-marketplace:
