import * as path from 'path'
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import tailwindcss from '@tailwindcss/vite'
import pkg from './package.json' with { type: 'json' }
import { resolve } from 'path'
import { fileURLToPath } from 'url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))

const twigRefreshPlugin = {
  name: 'twig-refresh',
  configureServer({ watcher, ws }) {
    watcher.add(resolve('../templates/**/*.twig'))
    watcher.on('change', function (path) {
      if (path.endsWith('.twig')) {
        ws.send({ type: 'full-reload' })
      }
    })
  },
}

process.env.VITE_APP_VERSION = pkg.version
if (process.env.NODE_ENV === 'production') {
  process.env.VITE_APP_BUILD_EPOCH = new Date().getTime().toString()
}

export default defineConfig({
  root: './assets',
  base: '/assets/',
  plugins: [twigRefreshPlugin, vue(), tailwindcss()],
  server: {
    port: 3003,
    cors: true,
    watch: { disableGlobbing: false },
    hmr: { protocol: 'ws', host: 'localhost', port: 3003 },
  },
  resolve: { alias: { '@': path.resolve(__dirname, './assets') } },
  build: {
    manifest: true,
    assetsDir: '',
    outDir: '../public/assets/',
    // Vite 8 switched to Lightning CSS for CSS minification by default, which rejects the
    // percentage-based media queries generated by our custom Tailwind breakpoints
    // (--breakpoint-90/92/94/98 in assets/style/main.css). Fall back to esbuild to keep the
    // previous, more permissive CSS minification behavior.
    cssMinify: 'esbuild',
    rolldownOptions: {
      input: {
        'main.ts': path.resolve(__dirname, 'assets/main.ts'),
      },
    },
  },
  define: { __VUE_PROD_HYDRATION_MISMATCH_DETAILS__: false },
})
