export enum AccountPageList {
  ACCOUNT = 'ACCOUNT',
  CONTACT_INFORMATION = 'CONTACT_INFORMATION',
  CONTACT_INFORMATION_PASSWORD_CHANGE = 'CONTACT_INFORMATION_PASSWORD_CHANGE',
  CONTACT_INFORMATION_EMAIL_EDIT = 'CONTACT_INFORMATION_EMAIL_EDIT',
  CONTACT_INFORMATION_DETAILS_EDIT = 'CONTACT_INFORMATION_DETAILS_EDIT',
  ADDRESSES = 'ADDRESSES',
  ADDRESS_EDIT = 'ADDRESS_EDIT',
  ADDRESS_CREATE = 'ADDRESS_CREATE',
  FAVORITES_LIST = 'FAVORITES_LIST',
  FAVORITES_DETAILS = 'FAVORITES_DETAILS',
  ORDERS = 'ORDERS',
  ORDER_DETAILS = 'ORDER_DETAILS',
  SAVED_CARTS = 'SAVED_CARTS',
  SAVED_CARTS_DETAILS = 'SAVED_CARTS_DETAILS',
  ORDERS_VALIDATION = 'ORDERS_VALIDATION',
}

export enum NewsPageList {
  NEWS = 'NEWS',
  NEWS_ITEM = 'NEWS_ITEM',
}

export enum CartPageList {
  RECAP = 'CART_RECAP',
  ADDRESSES = 'CART_ADRESS',
  PAYMENT = 'CART_PAYMENT',
  CONFIRMED = 'CART_CONFIRMED',
  PAYMENT_ERROR = 'PAYMENT_ERROR',
}

export enum MainPageList {
  HOME_PAGE = 'HOME_PAGE',
  CONTACT_PAGE = 'CONTACT_PAGE',
  MENTIONS_LEGALES_PAGE = 'MENTIONS_LEGALES_PAGE',
  CGU_PAGE = 'CGU_PAGE',
  POLITIQUE_DE_CONFIDENTIALITE = 'POLITIQUE_DE_CONFIDENTIALITE',
  PAGE_NOT_FOUND = 'PAGE_NOT_FOUND',
}

export enum ProductPageList {
  PRODUCTS = 'PRODUCTS',
  CATEGORIES = 'CATEGORIES',
  PRODUCT = 'PRODUCT',
  ACCORD_CADRE = 'ACCORD_CADRE',
}
