# https://qantis.atlassian.net/wiki/spaces/M2/pages/650412047/PROCESS+Donn+es+n+cessaires+nouvelle+MB#Options-du-channel-(channelOption)-%3A

parameters:
  channel_option_valid_keys:
    - 'BANNER_HOMEPAGE'
    - 'BANNER_TITLE_HOMEPAGE'
    - 'TEXT_FOOTER'
    - 'BANNER_FLASH_HOMEPAGE'
    - 'BANNER_SLIDER_HOMEPAGE'
    - 'RSE_HOMEPAGE'
    - 'SUPPLIER_PARTNERS_HOMEPAGE'
    - 'SUPPLIER_PARTNERS_HOMEPAGE_LIST'
    - 'EXPERT_CONTENT_HOMEPAGE'
    - 'FAVORITES'
    - 'PRE_HOME_IMAGE'
    - 'PRE_HOME_TITLE'
    - 'PRE_HOME_SUBTITLE'
    - 'PRE_HOME_LIST'
    - 'PRE_HOME_NOTATION'
    - 'SAVED_CARTS'
    - 'PROMOTIONAL_FAT'
    - 'CUSTOM_HEADER_CATEGORIES'
    - 'PRE_HOME_TEXT_LEFT_COLUMN'
    - 'PRE_HOME_TEXT_FIRST_CONNECTION_CHANGE_OF_PASSWORD'
    - 'PRE_HOME_BUTTON_FIRST_CONNECTION_CHANGE_OF_PASSWORD'
    - 'FOOTER_TITLE_ACCOUNT'
    - 'ACCOUNT_TEXT_LEFT_COLUMN'
    - 'CONTACT_TEXT_UNDER_TITLE'
    - 'HOMEPAGE_ACCORD_CADRE_CHANNEL_PROPERTY_VALUE_ID'
    - 'HOMEPAGE_PRODUCTS_SELECTION_CHANNEL_PROPERTY_VALUE_ID'
    - 'CUSTOM_CATEGORIES_NAME'
    - 'HAS_MANDAT_ADMIN_PAYMENT'
