# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
  uppler_env: '%env(UPPLER_ENV)%'
  uppler_api_url: '%env(UPPLER_API_URL)%'
  uppler_admin_client_id: '%env(UPPLER_ADMIN_CLIENT_ID)%'
  uppler_admin_client_secret: '%env(UPPLER_ADMIN_CLIENT_SECRET)%'
  uppler_webhook_secret: '%env(UPPLER_WEBHOOK_SECRET)%'
  http_cache_path: '%kernel.project_dir%/var/cache/%env(APP_ENV)%'
  #fichier qui stocke le token admin en cours
  uppler_admin_token_file: '%kernel.project_dir%/var/'
  #ttl entre 2 essais de reinit de password en minutes
  retry_ttl: 120
  ACCOUNTS_SUGAR_LINK: '%env(SUGAR_LINK)%'
  SUBSCRIPTION_MAIL_FROM: '%env(MAIL_FROM)%'
  SUBSCRIPTION_MAIL_TO: '%env(MAIL_TO)%'
  CONTACT_MAIL_FROM: '%env(MAIL_FROM)%'
  MAIL_CONTACT_SHOWCASE_TO: '%env(MAIL_TO)%'
  STELLANTIS_PARAMS:
    ACCORDS_IDS:
      PEUGEOT: '010148ae-5c2b-11ec-bfa4-0af08f946010'
      ALFA_ROMEO: 'e7b514bc-d469-11ed-b265-025bcd73cb12'
      DS: '0058a438-5c2b-11ec-b127-0af08f946010'
      OPEL: '00ddfc1e-5c2b-11ec-b75a-0af08f946010'
      FIAT: 'b828903e-d469-11ed-8695-067e628b0734'
      CITROEN: '00477df2-5c2b-11ec-a27b-0af08f946010'
      JEEP: 'd43c8e24-d469-11ed-a959-025bcd73cb12'
    ADHERENT_MAIL:
      FROM: '%env(MAIL_FROM)%'
      TO: '%env(ADH_SERV_MAIL_TO)%'
    STELLANTIS_MAIL:
      FROM: '%env(MAIL_FROM)%'
      TO: '%env(STELLANTIS_MAIL_TO)%'

imports:
  - { resource: services/ }
  - { resource: channels.yaml }
  - { resource: channel_option_keys.yaml }

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: '../src/'
    exclude: '../src/{DependencyInjection,Entity,Kernel.php,Serializer}'
  App\Twig\ViteAssetExtension:
    arguments:
      $env: '%env(APP_ENV)%'
      $manifest: '%kernel.project_dir%/public/assets/.vite/manifest.json'
      $cache: '@vite_cache_pool'

  Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler:
    arguments:
      - '%env(DATABASE_URL)%'
      - { lock_mode: 0 }

  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones
  App\EventListener\MaintenanceListener:
    arguments:
      - '@router'
    tags:
      - { name: kernel.event_listener, event: kernel.request }

  App\EventListener\ChannelListener:
    tags:
      - { name: doctrine.event_listener, event: postLoad }

  App\EventListener\AuthenticationListener:
    tags:
      - { name: kernel.event_listener, event: kernel.request }

  _instanceof:
    \App\Controller\ChannelRepositoryAwareControllerInterface:
      calls:
        - setChannelRepository: [ '@App\Repository\ChannelRepository' ]

    # SERVICES UPPLER
    App\Service\AbstractUpplerService:
      bind:
        $upplerEnv: '%uppler_env%'
        $adminClientId: '%uppler_admin_client_id%'
        $adminClientSecret: '%uppler_admin_client_secret%'
        $adminTokenFile: '%uppler_admin_token_file%'
        $httpCachePath: '%http_cache_path%'

  # Voter
  App\Security\Voter\FavoriteVoter:
    tags: [ { name: security.voter } ]

  App\Security\Voter\SavedCartVoter:
    tags: [ { name: security.voter } ]

  App\DataFixtures\Story\ChannelStory:
    arguments:
      $channels: '%channels%'

  App\Service\Channel\ChannelOptionsBuilder:
    arguments:
      $validKeys: '%channel_option_valid_keys%'

  App\Service\AccordCadreSubscriptionService:
    arguments:
      $stellantisParams: '%STELLANTIS_PARAMS%'

  App\Service\AccordCadreSubscription\SubscriptionMailerService:
    arguments:
      $sugarLink: '%env(SUGAR_LINK)%'
      $emailFrom: '%env(MAIL_FROM)%'
      $stellantisParams: '%STELLANTIS_PARAMS%'

  App\Service\RequestContactMailerService:
    arguments:
      $sugarLink: '%env(SUGAR_LINK)%'
      $emailFrom: '%env(MAIL_FROM)%'

  Symfony\Component\DependencyInjection\ContainerInterface: '@service_container'

  Symfony\Component\Security\Http\AccessMapInterface: '@security.access_map'

  App\EventListener\JWTExceptionListener:
    tags:
      - {
        name: 'kernel.event_listener',
        event: 'lexik_jwt_authentication.on_jwt_expired',
        method: 'onJWTException',
      }
      - {
        name: 'kernel.event_listener',
        event: 'lexik_jwt_authentication.on_jwt_invalid',
        method: 'onJWTException',
      }
