# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
  app_domain: '%env(APP_DOMAIN)%'
  uppler_env: '%env(UPPLER_ENV)%'
  uppler_api_url: '%env(UPPLER_API_URL)%'
  uppler_admin_client_id: '%env(UPPLER_ADMIN_CLIENT_ID)%'
  uppler_admin_client_secret: '%env(UPPLER_ADMIN_CLIENT_SECRET)%'
  http_cache_path: '%kernel.project_dir%/var/cache/%env(APP_ENV)%'
  #fichier qui stocke le token admin en cours
  uppler_admin_token_file: '%kernel.project_dir%/var/'
  #ttl entre 2 essais de reinit de password en minutes
  retry_ttl: 120
  #Expéditeur des mails
  mail_from: '%env(MAIL_FROM)%'
  mail_contact: '%env(MAIL_CONTACT)%'
  mail_admin: '%env(MAIL_ADMIN)%'
  uppler_url_source_product_img: '%env(UPPLER_URL_SOURCE_PRODUCT_IMG)%'
  uppler_url_source_list_product_img: '%env(UPPLER_URL_SOURCE_LIST_PRODUCT_IMG)%'
  uppler_url_source_seller_img: '%env(UPPLER_URL_SOURCE_SELLER_IMG)%'
  SUBSCRIPTION_MAIL_SUGAR_LINK: '%env(SUGAR_LINK)%'
  SUBSCRIPTION_MAIL_FROM: '%env(MAIL_FROM)%'
  SUBSCRIPTION_MAIL_TO: '%env(MAIL_TO)%'
  STELLANTIS_MAILING:
    ACCORDS_IDS:
      - '010148ae-5c2b-11ec-bfa4-0af08f946010' #PEUGEOT
      - 'e7b514bc-d469-11ed-b265-025bcd73cb12' #ALFA ROMEO
      - '0058a438-5c2b-11ec-b127-0af08f946010' #DS
      - '00ddfc1e-5c2b-11ec-b75a-0af08f946010' #OPEL
      - 'b828903e-d469-11ed-8695-067e628b0734' #FIAT
      - '00477df2-5c2b-11ec-a27b-0af08f946010' #CITROEN
      - 'd43c8e24-d469-11ed-a959-025bcd73cb12' #JEEP
    ADHERENT_MAIL:
      FROM:
        '%env(MAIL_FROM)%'
      TO:
        '%env(ADH_SERV_MAIL_TO)%'
    STELLANTIS_MAIL:
      FROM:
        '%env(MAIL_FROM)%'
      TO:
        '%env(STELLANTIS_MAIL_TO)%'
      CC:
        '%env(STELLANTIS_MAIL_CC)%'


imports:
  - { resource: services/ }
  - { resource: channels.yaml }
  - { resource: channel_option_keys.yaml }

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: '../src/'
    exclude: '../src/{DependencyInjection,Entity,Kernel.php,Serializer}'
  App\Twig\ViteAssetExtension:
    arguments:
      $env: '%env(APP_ENV)%'
      $manifest: '%kernel.project_dir%/public/assets/manifest.json'
      $cache: '@vite_cache_pool'

  Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler:
    arguments:
      - '%env(DATABASE_URL)%'

  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones
  app.uppler_authenticator:
    class: App\Security\UpplerAuthenticator
    parent: lexik_jwt_authentication.security.jwt_authenticator
    autowire: true

  App\EventListener\MaintenanceListener:
    arguments:
      - '@router'
    tags:
      - { name: kernel.event_listener, event: kernel.request }

  App\EventListener\ChannelListener:
    tags:
      - { name: doctrine.event_listener, event: postLoad }

  _instanceof:
    \App\Controller\ChannelRepositoryAwareControllerInterface:
      calls:
        - setChannelRepository: [ '@App\Repository\ChannelRepository' ]

    # SERVICES UPPLER
    App\Service\AbstractUpplerService:
      bind:
        $upplerEnv: '%uppler_env%'
        $adminClientId: '%uppler_admin_client_id%'
        $adminClientSecret: '%uppler_admin_client_secret%'
        $adminTokenFile: '%uppler_admin_token_file%'
        $httpCachePath: '%http_cache_path%'
        $appDomain: '%app_domain%'

  # Voter
  App\Security\Voter\FavoriteVoter:
    tags: [ { name: security.voter } ]

  App\Security\Voter\SavedCartVoter:
    tags: [ { name: security.voter } ]

  Sentry\Integration\IgnoreErrorsIntegration:
    arguments:
      $options:
        ignore_exceptions:
          - Symfony\Component\HttpKernel\Exception\NotFoundHttpException
          - Symfony\Component\Security\Core\Exception\AuthenticationException

  App\DataFixtures\Story\ChannelStory:
    arguments:
      $channels: '%channels%'

  App\DataProvider\AccountCollectionDataProvider:
    arguments:
      $collectionExtensions: !tagged api_platform.doctrine.orm.query_extension.collection

  App\DataProvider\UserMeItemDataProvider:
    arguments:
      $itemExtensions: !tagged api_platform.doctrine.orm.query_extension.item

  App\Service\Channel\ChannelOptionsBuilder:
    arguments:
      $validKeys: '%channel_option_valid_keys%'
