# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
  app_domain: '%env(APP_DOMAIN)%'
  uppler_env: '%env(UPPLER_ENV)%'
  uppler_api_url: '%env(UPPLER_API_URL)%'
  uppler_admin_client_id: '%env(UPPLER_ADMIN_CLIENT_ID)%'
  uppler_admin_client_secret: '%env(UPPLER_ADMIN_CLIENT_SECRET)%'
  http_cache_path: '%kernel.project_dir%/var/cache/%env(APP_ENV)%'
  #fichier qui stocke le token admin en cours
  uppler_admin_token_file: '%kernel.project_dir%/var/'
  #ttl entre 2 essais de reinit de password en minutes
  retry_ttl: 120
  #Expéditeur des mails
  mail_from: '%env(MAIL_FROM)%'
  mail_contact: '%env(MAIL_CONTACT)%'
  mail_admin: '%env(MAIL_ADMIN)%'
  uppler_url_source_product_img: '%env(UPPLER_URL_SOURCE_PRODUCT_IMG)%'
  uppler_url_source_list_product_img: '%env(UPPLER_URL_SOURCE_LIST_PRODUCT_IMG)%'
  uppler_url_source_seller_img: '%env(UPPLER_URL_SOURCE_SELLER_IMG)%'
  SUBSCRIPTION_MAIL_SUGAR_LINK: '%env(SUGAR_LINK)%'
  SUBSCRIPTION_MAIL_FROM: '%env(MAIL_FROM)%'
  SUBSCRIPTION_MAIL_TO: '%env(MAIL_TO)%'
services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'
  App\Twig\ViteAssetExtension:
    arguments:
      $env: '%env(APP_ENV)%'
      $manifest: '%kernel.project_dir%/public/assets/manifest.json'
      $cache: '@vite_cache_pool'

  Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler:
    arguments:
      - '%env(DATABASE_URL)%'
      - { 'ttl': 3600 }

  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones
  App\Tests\Resources\DataFixtures\:
    resource: '../tests/Resources/DataFixtures'
    tags: ['doctrine.fixture.orm']
  app.uppler_authenticator:
    class: App\Security\UpplerAuthenticator
    parent: lexik_jwt_authentication.security.jwt_authenticator
    autowire: true

  App\DataFixtures\UserFixtures:
    arguments:
      $env: '%uppler_env%'

  App\Service\HttpClientProvider:
    arguments:
      $env: '%uppler_env%'
      $apiUrl: '%uppler_api_url%'
      $adminClientId: '%uppler_admin_client_id%'
      $adminClientSecret: '%uppler_admin_client_secret%'
      $adminTokenFile: '%uppler_admin_token_file%'
      $httpCachePath: '%http_cache_path%'

  App\Service\UpplerAuthenticationService:
    parent: App\Service\HttpClientProvider

  App\Service\UpplerSellerService:
    parent: App\Service\HttpClientProvider

  App\Service\UpplerBuyerCompanyService:
    parent: App\Service\HttpClientProvider

  App\Service\UpplerRepositoryService:
    parent: App\Service\HttpClientProvider

  App\Service\UpplerAccountService:
    parent: App\Service\HttpClientProvider

  App\Service\UpplerCartService:
    parent: App\Service\HttpClientProvider
    arguments:
      $appDomain: '%app_domain%'

  App\Service\UpplerProductService:
    parent: App\Service\HttpClientProvider

  App\Service\UpplerDynamicEntityService:
    parent: App\Service\HttpClientProvider
    arguments:
      $upplerUrlSourceProductImg: '%uppler_url_source_product_img%'
      $upplerUrlSourceSellerImg: '%uppler_url_source_seller_img%'
